### ISSUE TITLE
sequence diagram for M2

### ISSUE THREAD

**Issue by TeeNyKoH** [waltertan98/ICT2101-2201-Team-Project#121]
to be done by 29/10/22

**Comment by banananiee** [comment]
Meet up on 13/10/22 to discuss and work on the sequence diagram

**Comment by banananiee** [comment]
Checked and edited each sequence diagram on 20/10/22

**Comment by AiXin18** [comment]
Final Check all the sequence diagram and have added all the diagrams into the report on 21/10/2022
