### ISSUE TITLE
Improve UI in figma

### ISSUE THREAD

**Issue by waltertan98** [waltertan98/ICT2101-2201-Team-Project#139]

**Comment by AiXin18** [comment]
Ai Xin - Done, 13 hours, 28/10/2022

**Comment by waltertan98** [comment]
completed 29/10/22
20 hours
edited 
-allocation page by all
![Image](https://user-images.githubusercontent.com/93696258/198710801-67528d40-87f2-40c5-b5b0-2e3782666f5f.png)
![Image](https://user-images.githubusercontent.com/93696258/198710842-f055815d-5234-4757-9316-204a92c072ba.png)
-manager landing page by ai xin
-staff landing page by ai xin
-delete/edit account page by ai xin
-create account page by ai xin
![Image](https://user-images.githubusercontent.com/93696258/198711021-e56d570c-8f37-4a75-997b-0168689759e1.png)
created
-schedule generator pop up by chun guan
-adding team pop up by chun guan
-schedule confirmation pop up by chun guan
-approval of rejection requst pop up by ai xin
![Image](https://user-images.githubusercontent.com/93696258/198711129-06d26f76-37f2-4d1b-beb4-9c3494e13956.png)
![Image](https://user-images.githubusercontent.com/93696258/198711170-25350731-4793-484c-a097-b0c3f6418d99.png)
