### ISSUE TITLE
Finalise component diagram/architecture and design pattern

### ISSUE THREAD

**Issue by TeeNyKoH** [waltertan98/ICT2101-2201-Team-Project#146]
due 29/10/22

**Comment by TeeNyKoH** [comment]
Component diagram



![Image](https://user-images.githubusercontent.com/25479231/197577029-492feca8-19f6-4b8e-9ef5-03e47471d779.png)

**Comment by waltertan98** [comment]
Finalise component diagram/architecture and design pattern
27/10/22 by - Anna and CG
6 hours
