### ISSUE TITLE
finalise class diagram

### ISSUE THREAD

**Issue by TeeNyKoH** [waltertan98/ICT2101-2201-Team-Project#147]

**Comment by TeeNyKoH** [comment]
Class diagram


![Image](https://user-images.githubusercontent.com/25479231/197578944-842ef1bb-f6d7-4a80-8dda-791324731988.png)

**Comment by waltertan98** [comment]
class diagram finalised 
27/10/22
3 hours 
![Image](https://user-images.githubusercontent.com/93696258/198283969-bcc0cd41-e834-4d73-b8c7-916e83efa2f0.jpg)
