### ISSUE TITLE
Thursday meeting (27/10/22)

### ISSUE THREAD

**Issue by TeeNyKoH** [waltertan98/ICT2101-2201-Team-Project#149]

**Comment by TeeNyKoH** [comment]
to-do on Thursday meeting 27/10/22
m2 report point 5
include all sequence diagram
m2 report point 7
m2 report point 9



(Feel free to add more on it)

**Comment by waltertan98** [comment]
m2 point 5 completed - by Anna and CG
m2 point 9 pasted
27/10/22

**Comment by waltertan98** [comment]
meeting ended 
point 7 - reflection pushed to 28/10/22

**Comment by AiXin18** [comment]
Things completed on (Ai Xin - 27/10/2022)
- Edited all the GUI in Figma
- Edited the tables for section 4.1 (Software Estimation)
- Edited the M2 report arrangement to make it neater

**Comment by waltertan98** [comment]
completed all points 29/10/22
20 hours
